service: kleros-microservices
provider:
    name: aws
    runtime: nodejs8.10
    stage: '${opt:stage, self:custom.defaultStage}'
    region: us-east-2
package:
    exclude:
        - .env
environment:
    AWS_REGION: '${self:provider.region}'
plugins:
    - serverless-kms-secrets
    - serverless-iam-roles-per-function
    - serverless-aws-documentation
custom:
    defaultStage: staging
    environments:
        staging: STAGING
        production: PRODUCTION
    serverless-kms-secrets:
        secretsFile: 'kms-secrets.${self:provider.region}.yml'
    kmsSecrets: '${file(kms-secrets.${self:provider.region}.yml)}'
    documentation:
        info:
            version: '1'
            title: 'Kleros Microservices'
            description: 'Collection of Kleros microservices.'
        resources:
            - {path: doges-on-trial, description: 'Microservices for the Doges on Trial dapp.'}
        models:
            - {name: ErrorResponse, description: 'An error response.', contentType: application/json, schema: '${file(src/models/error.json)}'}
            - {name: PostDogesOnTrialDogeImagesResponse, description: 'The response for postDogesOnTrialDogeImages.', contentType: application/json, schema: '${file(src/doges-on-trial/models/doge-images.json):post.response}'}
functions:
    postDogesOnTrialDogeImages:
        handler: src/doges-on-trial/doge-images.post
        events:
            - {http: {path: doges-on-trial/doge-images, method: post, cors: true}}
        environment:
            INFURA_URL: '${self:custom.kmsSecrets.secrets.${self:custom.environments.${self:provider.stage}}_INFURA_URL}'
            ARBITRABLE_PERMISSION_LIST_ADDRESS: '${self:custom.kmsSecrets.secrets.${self:custom.environments.${self:provider.stage}}_ARBITRABLE_PERMISSION_LIST_ADDRESS}'
        iamRoleStatements:
            - {Effect: Allow, Action: ['KMS:Decrypt'], Resource: '${self:custom.kmsSecrets.keyArn}'}
            - {Effect: Allow, Action: ['s3:PutObject'], Resource: 'arn:aws:s3:::${self:provider.stage}-doges-on-trial-doge-images'}
        documentation:
            summary: 'Upload a doge image.'
            description: 'The image hash must be added to the contract first.'
            requestBody: {description: 'The image''s raw bytes.'}
            requestHeaders: [{name: 'Content-Type: application/octet-stream'}]
            methodResponses: [{statusCode: '200', responseModels: {application/json: PostDogesOnTrialDogeImagesResponse}}, {statusCode: '400', responseModels: {application/json: ErrorResponse}}]
